server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_user?useSSL=false
    username: root
    password: Decucin123
    driver-class-name: com.mysql.cj.jdbc.Driver
#      discovery:
#        cluster-name: HZ      # 集群名称
#  shardingsphere:
#    sharding:
#      default-database-strategy:
#      tables:
#      discovery:
#        cluster-name: HZ
mybatis:
  type-aliases-package: com.decucin.user.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.decucin: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS


#eureka:
#  client:
#    service-url:  # eureka地址信息
#      defaultZone: http://127.0.0.1:10086/eureka