server:
  port: 10010

spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service # 自定义的唯一标识，必须唯一
          uri: lb://userservice # 路由的目标地址，也可使用http://localhost:8081写死，但不推荐
          predicates:   # 判断请求是否符合规则
            - Path=/user/** # 路径断言，判断是否以/user开头，如果是则符合
#          filters: # 过滤器
#            - AddRequestHeader=Truth,Decucin is awesome!  # 添加请求头
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/order/**
#            - After=2031-01-20T17:42:47.789-07:00[America/Denver]
      default-filters: # 注意这里和routes一级
        - AddRequestHeader=Truth,Decucin is awesome!  # 添加请求头
        globalcors:
          add-to-simple-url-handler-mapping: true # 防止option请求被拦截
          cors-configurations:
            '[/**]':
              allowedOrigins: # 允许哪些网站的跨域请求
                - "http://localhost:8090"
                - "http://www.leyou.com"
              allowedMethods:
                - "GET"
                - "POST"
                - "DELETE"
                - "PUT"
                - "OPTIONS"
              allowedHeaders: "*" # 允许在请求中携带的头信息
              allowCredentials: true  # 是否允许携带cookie
              maxAge: 360000  # 本次跨域的有效期
