erver:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: Decucin123
    driver-class-name: com.mysql.cj.jdbc.Driver
#  application:
#    name: orderservice
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务端地址（实际上服务端就是之前安装的本机服务）
#      discovery:
#        cluster-name: KM
#        namespace: 42968204-428b-449e-a9a5-cf2304791142
#        ephemeral: false  # 是否是临时实例


mybatis:
  type-aliases-package: com.decucin.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.decucin: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

#eureka:
#  client:
#    service-url:  # eureka地址信息
#      defaultZone: http://127.0.0.1:10086/eureka


      
userservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

ribbon:
  eager-load:
    enabled: true # 开启指定加载
    clients:
      - userservice
